# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

class FibonacciNumbers
  attr_accessor :fibonacciNumbersArray

  def initialize
    @fibonacciNumbersArray = [0,1]
  end

  def fibonacci(max)
    i = 2
    sum = 0
      while sum < max
        sum = @fibonacciNumbersArray[i-1] +@fibonacciNumbersArray[i-2]
        @fibonacciNumbersArray << sum
        i +=1
      end
      print @fibonacciNumbersArray
    # @fibonacciNumbersArray
    even_num = 0
    @fibonacciNumbersArray.each do |fbn|
      if fbn %2 == 0
        print fbn
      else
        @fibonacciNumbersArray
      end
    end
  end
end

fibon = FibonacciNumbers.new
print fibon.fibonacci(4000000)
